# Generated by Django 4.2.1 on 2023-10-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0003_chapiter_comment_etudiant_formateur_formation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
