# Generated by Django 4.2.1 on 2023-10-05 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0005_tag_formation_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formation',
            name='date',
            field=models.DateField(),
        ),
    ]
