# Generated by Django 4.2.1 on 2023-10-05 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0006_alter_formation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='formation',
            name='is_for_kids',
            field=models.BooleanField(default=False),
        ),
    ]
