# Generated by Django 4.2.1 on 2023-10-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0007_etudiant_date_of_birth_formation_is_for_kids'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='formations',
            field=models.ManyToManyField(blank=True, to='cubaapp.formation'),
        ),
    ]
