# Generated by Django 4.2.1 on 2023-10-06 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0009_chapiterresult'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapiterresult',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
