# Generated by Django 4.2.1 on 2023-10-07 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cubaapp', '0010_alter_chapiterresult_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etudiant',
            name='email',
        ),
        migrations.AddField(
            model_name='chapiter',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
